 -- Table: edge
 
CREATE TABLE edge
(
    pgraphId bigint PRIMARY KEY,
    fromNodeId bigint PRIMARY KEY,
    toNodeId bigint PRIMARY KEY
)
WITH(OIDS=FALSE);
 
ALTER TABLE edge OWNER TO "sobek";
ALTER TABLE edge ADD CONSTRAINT graphIdFk FOREIGN KEY (pgraphId) REFERENCES pgraph (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE edge ADD CONSTRAINT fromNodeIdFk FOREIGN KEY (fromNodeId) REFERENCES node (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE edge ADD CONSTRAINT toNodeIdFk FOREIGN KEY (toNodeId) REFERENCES node (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
 